apiVersion: v2
name: compartment
description: Compartment platform runtime for Kubernetes
type: application
version: 0.1.0
appVersion: 0.11.0
kubeVersion: '>=1.30.0-0'
dependencies:
  - name: capsule
    version: 0.13.11
    repository: https://projectcapsule.github.io/charts
