apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "compartment.fullname" . }}
  labels:
    {{- include "compartment.labels" . | nindent 4 }}
data:
  COMPARTMENT_API_BIND_HOST: "0.0.0.0"
  COMPARTMENT_API_INTERNAL_HOST: {{ printf "%s-api" (include "compartment.fullname" .) | quote }}
  COMPARTMENT_API_PORT: {{ .Values.ports.api | quote }}
  COMPARTMENT_ARTIFACT_REGISTRY_HOST: {{ printf "%s-registry-auth" (include "compartment.fullname" .) | quote }}
  COMPARTMENT_ARTIFACT_REGISTRY_PORT: {{ .Values.ports.registry | quote }}
  COMPARTMENT_ARTIFACT_REGISTRY_INTERNAL_HOST: {{ printf "%s-registry-auth" (include "compartment.fullname" .) | quote }}
  COMPARTMENT_ARTIFACT_REGISTRY_INTERNAL_PORT: {{ .Values.ports.registry | quote }}
  COMPARTMENT_ARTIFACT_REGISTRY_READ_USERNAME: {{ .Values.registry.readUsername | quote }}
  COMPARTMENT_ARTIFACT_REGISTRY_WRITE_USERNAME: {{ .Values.registry.writeUsername | quote }}
  COMPARTMENT_BASE_DOMAIN: {{ .Values.platform.baseDomain | quote }}
  COMPARTMENT_CADDY_TLS_MODE: {{ .Values.platform.tlsMode | quote }}
  COMPARTMENT_DOCKER_NAMESPACE: {{ .Release.Name | quote }}
  COMPARTMENT_EDGE_BIND_HOST: "0.0.0.0"
  COMPARTMENT_EDGE_INTERNAL_HOST: {{ printf "%s-edge" (include "compartment.fullname" .) | quote }}
  COMPARTMENT_EDGE_PORT: {{ .Values.ports.edge | quote }}
  COMPARTMENT_ENV: self-hosted
  COMPARTMENT_LOG_LEVEL: {{ .Values.platform.logLevel | quote }}
  COMPARTMENT_PUBLIC_PROTOCOL: {{ .Values.platform.publicProtocol | quote }}
  COMPARTMENT_PUBLIC_HTTP_PORT: {{ .Values.ports.http | quote }}
  COMPARTMENT_PUBLIC_HTTPS_PORT: {{ .Values.ports.https | quote }}
  COMPARTMENT_TRUSTED_OUTBOUND_HOSTS: {{ .Values.platform.trustedOutboundHosts | quote }}
  COMPARTMENT_WORKER_POLL_INTERVAL_MS: {{ .Values.platform.workerPollIntervalMs | quote }}
  BUILDKIT_ADDR: {{ printf "tcp://%s-buildkit:%v" (include "compartment.fullname" .) .Values.ports.buildkit | quote }}
  COMPARTMENT_NODE_AGENT_SOCKET: /var/run/compartment/node/agent.sock
  COMPARTMENT_SYSTEM_API_SOCKET: /var/run/compartment/api/system-api.sock
  COMPARTMENT_RUNTIME_DEFAULT_UPSTREAM_HOST: host.docker.internal
  COMPARTMENT_CUSTOM_TLS_DIR: /etc/compartment/tls
  COMPARTMENT_MANAGED_DOMAIN_BROKER_TOKEN: ""
  COMPARTMENT_MANAGED_DOMAIN_BROKER_URL: ""
  COMPARTMENT_PUBLIC_INGRESS_IPV4: ""
  COMPARTMENT_PUBLIC_INGRESS_IPV6: ""
  COMPARTMENT_RESOURCE_BACKUP_DIR: /var/lib/compartment/resource-backups
  COMPARTMENT_SOURCE_ARCHIVE_DIR: /var/lib/compartment/source-archives
  COMPARTMENT_SOURCE_ARCHIVE_MAX_BYTES: {{ .Values.platform.sourceArchiveMaxBytes | quote }}
  COMPARTMENT_AUDIT_RETENTION_DAYS: {{ .Values.platform.auditRetentionDays | quote }}
  COMPARTMENT_AUDIT_RETENTION_CLEANUP_CRON: {{ .Values.platform.auditCleanupCron | quote }}
  COMPARTMENT_AUDIT_RETENTION_CLEANUP_BATCH_SIZE: {{ .Values.platform.auditCleanupBatchSize | quote }}
  COMPARTMENT_AUDIT_RETENTION_CLEANUP_MAX_BATCHES: {{ .Values.platform.auditCleanupMaxBatches | quote }}
  COMPARTMENT_AUDIT_FILE_SINK_ENABLED: {{ .Values.platform.auditFileSinkEnabled | quote }}
  COMPARTMENT_AUDIT_FILE_SINK_DIR: /var/lib/compartment/audit-logs
  COMPARTMENT_AUDIT_FILE_SINK_ROTATE_INTERVAL: {{ .Values.platform.auditFileSinkRotateInterval | quote }}
  COMPARTMENT_AUDIT_FILE_SINK_ROTATE_SIZE: {{ .Values.platform.auditFileSinkRotateSize | quote }}
  COMPARTMENT_AUDIT_FILE_SINK_RETENTION_FILES: {{ .Values.platform.auditFileSinkRetentionFiles | quote }}
  COMPARTMENT_ROLLBACK_RETENTION_LIMIT: ""
  COMPARTMENT_SESSION_TTL: {{ .Values.platform.sessionTtl | quote }}
  COMPARTMENT_THROTTLE_AUTH_LOGIN_ROUTE_MAX_REQUESTS: "30"
  COMPARTMENT_THROTTLE_AUTH_LOGIN_ROUTE_WINDOW: 1m
  COMPARTMENT_THROTTLE_AUTH_LOGIN_SOURCE_MAX_FAILURES: "20"
  COMPARTMENT_THROTTLE_AUTH_LOGIN_SOURCE_WINDOW: 5m
  COMPARTMENT_THROTTLE_AUTH_LOGIN_SOURCE_BLOCK: 15m
  COMPARTMENT_THROTTLE_AUTH_LOGIN_ACCOUNT_MAX_FAILURES: "10"
  COMPARTMENT_THROTTLE_AUTH_LOGIN_ACCOUNT_WINDOW: 10m
  COMPARTMENT_THROTTLE_AUTH_LOGIN_ACCOUNT_BLOCK: 30m
  COMPARTMENT_THROTTLE_AUTH_LOGIN_SOURCE_ACCOUNT_MAX_FAILURES: "5"
  COMPARTMENT_THROTTLE_AUTH_LOGIN_SOURCE_ACCOUNT_WINDOW: 1m
  COMPARTMENT_THROTTLE_AUTH_LOGIN_SOURCE_ACCOUNT_BLOCK: 10m
  COMPARTMENT_THROTTLE_AUTH_ACTIVATE_ROUTE_MAX_REQUESTS: "10"
  COMPARTMENT_THROTTLE_AUTH_ACTIVATE_ROUTE_WINDOW: 1m
  COMPARTMENT_THROTTLE_AUTH_ACTIVATE_SOURCE_MAX_FAILURES: "15"
  COMPARTMENT_THROTTLE_AUTH_ACTIVATE_SOURCE_WINDOW: 10m
  COMPARTMENT_THROTTLE_AUTH_ACTIVATE_SOURCE_BLOCK: 30m
  COMPARTMENT_THROTTLE_AUTH_ACTIVATE_SUBJECT_MAX_FAILURES: "5"
  COMPARTMENT_THROTTLE_AUTH_ACTIVATE_SUBJECT_WINDOW: 30m
  COMPARTMENT_THROTTLE_AUTH_ACTIVATE_SUBJECT_BLOCK: 60m
  COMPARTMENT_THROTTLE_AUTH_ACTIVATE_SOURCE_SUBJECT_MAX_FAILURES: "3"
  COMPARTMENT_THROTTLE_AUTH_ACTIVATE_SOURCE_SUBJECT_WINDOW: 10m
  COMPARTMENT_THROTTLE_AUTH_ACTIVATE_SOURCE_SUBJECT_BLOCK: 30m
  COMPARTMENT_THROTTLE_AUTH_RESET_PASSWORD_ROUTE_MAX_REQUESTS: "10"
  COMPARTMENT_THROTTLE_AUTH_RESET_PASSWORD_ROUTE_WINDOW: 1m
  COMPARTMENT_THROTTLE_AUTH_RESET_PASSWORD_SOURCE_MAX_FAILURES: "15"
  COMPARTMENT_THROTTLE_AUTH_RESET_PASSWORD_SOURCE_WINDOW: 10m
  COMPARTMENT_THROTTLE_AUTH_RESET_PASSWORD_SOURCE_BLOCK: 30m
  COMPARTMENT_THROTTLE_AUTH_RESET_PASSWORD_SUBJECT_MAX_FAILURES: "5"
  COMPARTMENT_THROTTLE_AUTH_RESET_PASSWORD_SUBJECT_WINDOW: 30m
  COMPARTMENT_THROTTLE_AUTH_RESET_PASSWORD_SUBJECT_BLOCK: 60m
  COMPARTMENT_THROTTLE_AUTH_RESET_PASSWORD_SOURCE_SUBJECT_MAX_FAILURES: "3"
  COMPARTMENT_THROTTLE_AUTH_RESET_PASSWORD_SOURCE_SUBJECT_WINDOW: 10m
  COMPARTMENT_THROTTLE_AUTH_RESET_PASSWORD_SOURCE_SUBJECT_BLOCK: 30m
