{{- include "compartment.applyRetainedInstallState" . -}}
{{- if eq .Values.platform.startupStage "full" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "compartment.fullname" . }}-waiter
  labels:
    {{- include "compartment.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "compartment.fullname" . }}-worker
  labels:
    {{- include "compartment.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "compartment.fullname" . }}-api-migrate-reader
  labels:
    {{- include "compartment.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "compartment.fullname" . }}-api-migrate-reader
  labels:
    {{- include "compartment.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "compartment.fullname" . }}-api-migrate-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "compartment.fullname" . }}-waiter
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: {{ include "compartment.fullname" . }}-worker
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: {{ include "compartment.fullname" . }}-project-provisioner
    namespace: {{ .Release.Namespace }}
{{- end }}
