{{- if and .Values.buildkit.enabled (eq .Values.platform.startupStage "full") }}
{{- $platformSecret := lookup "v1" "Secret" .Release.Namespace (include "compartment.fullname" .) -}}
{{- $password := required "install the foundation stage first or set secrets.registryWritePassword" (default (dig "data" "registry-write-password" "" $platformSecret | b64dec) .Values.secrets.registryWritePassword) -}}
{{- $auth := printf "%s:%s" .Values.registry.writeUsername $password | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compartment.fullname" . }}-registry-client
  namespace: {{ .Values.buildkit.namespace }}
  labels:
    {{- include "compartment.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ dict "auths" (dict (printf "%s-registry-auth.%s.svc:%v" (include "compartment.fullname" .) .Release.Namespace .Values.ports.registry) (dict "username" .Values.registry.writeUsername "password" $password "auth" $auth)) | toJson | quote }}
{{- end }}
