{{- if .Values.buildkit.createRuntimeClass }}
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: {{ required "buildkit.runtimeClassName is required when createRuntimeClass is true" .Values.buildkit.runtimeClassName }}
  labels:
    {{- include "compartment.labels" . | nindent 4 }}
handler: {{ .Values.buildkit.runtimeHandler }}
{{- end }}
{{- if and .Values.tenantRuntime.createRuntimeClass (not (and .Values.buildkit.createRuntimeClass (eq .Values.tenantRuntime.runtimeClassName .Values.buildkit.runtimeClassName))) }}
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: {{ required "tenantRuntime.runtimeClassName is required when createRuntimeClass is true" .Values.tenantRuntime.runtimeClassName }}
  labels:
    {{- include "compartment.labels" . | nindent 4 }}
handler: {{ .Values.tenantRuntime.runtimeHandler }}
{{- end }}
