DROP INDEX "git_provider_registrations_active_owner_unique";--> statement-breakpoint
DROP INDEX "git_provider_registrations_pending_owner_unique";--> statement-breakpoint
ALTER TABLE "operations" ADD COLUMN "organization_id" text;--> statement-breakpoint
ALTER TABLE "git_provider_registrations" ADD COLUMN "organization_id" text;--> statement-breakpoint
UPDATE "git_provider_registrations" SET "organization_id" = substring("webhook_url" from '/v1/sources/git/providers/github/organizations/([^/]+)/registrations/[^/]+/webhook$');--> statement-breakpoint
ALTER TABLE "git_provider_registrations" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
UPDATE "operations" SET "organization_id" = "organizations"."id" FROM "organizations" WHERE "operations"."target_type" = 'organization' AND "operations"."target_id" = "organizations"."id";--> statement-breakpoint
UPDATE "operations" SET "organization_id" = "projects"."organization_id" FROM "environments" JOIN "projects" ON "projects"."id" = "environments"."project_id" WHERE "operations"."organization_id" IS NULL AND "operations"."target_type" = 'environment' AND "operations"."target_id" = "environments"."id";--> statement-breakpoint
UPDATE "operations" SET "organization_id" = "projects"."organization_id" FROM "project_resources" JOIN "environments" ON "environments"."id" = "project_resources"."environment_id" JOIN "projects" ON "projects"."id" = "environments"."project_id" WHERE "operations"."organization_id" IS NULL AND "operations"."target_type" = 'resource' AND "operations"."target_id" = "project_resources"."id";--> statement-breakpoint
UPDATE "operations" SET "organization_id" = "projects"."organization_id" FROM "deployments" JOIN "environments" ON "environments"."id" = "deployments"."environment_id" JOIN "projects" ON "projects"."id" = "environments"."project_id" WHERE "operations"."organization_id" IS NULL AND "deployments"."operation_id" = "operations"."id";--> statement-breakpoint
UPDATE "operations" SET "organization_id" = "projects"."organization_id" FROM "resource_backups" JOIN "project_resources" ON "project_resources"."id" = "resource_backups"."project_resource_id" JOIN "environments" ON "environments"."id" = "project_resources"."environment_id" JOIN "projects" ON "projects"."id" = "environments"."project_id" WHERE "operations"."organization_id" IS NULL AND "resource_backups"."operation_id" = "operations"."id";--> statement-breakpoint
ALTER TABLE "operations" ADD CONSTRAINT "operations_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "git_provider_registrations" ADD CONSTRAINT "git_provider_registrations_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "git_provider_registrations_active_owner_unique" ON "git_provider_registrations" USING btree ("organization_id","provider_type","provider_host","repository_owner") WHERE "git_provider_registrations"."status" = 'active';--> statement-breakpoint
CREATE UNIQUE INDEX "git_provider_registrations_pending_owner_unique" ON "git_provider_registrations" USING btree ("organization_id","provider_type","provider_host","repository_owner") WHERE "git_provider_registrations"."status" = 'pending';
