import type {
  AccessAssignmentScopeType,
  AccessSummaryLabel,
  CompartmentMembershipRole,
  PermissionFamilyDefinition,
  PermissionKey,
} from './access.contract.types';

export const accessAssignmentScopeTypeValues: readonly [AccessAssignmentScopeType, ...AccessAssignmentScopeType[]] = [
  'organization',
  'project',
  'environment',
];

export const compartmentMembershipRoleValues: readonly [CompartmentMembershipRole, ...CompartmentMembershipRole[]] = [
  'admin',
  'deployer',
  'readonly',
  'viewer',
];

export const accessSummaryLabelValues: readonly [AccessSummaryLabel, ...AccessSummaryLabel[]] = [
  'Custom',
  'Deploy',
  'Full access',
  'Limited view',
  'Membership only',
  'Read-only',
];

export const permissionKeyValues: readonly [PermissionKey, ...PermissionKey[]] = [
  'organization.project.create',
  'organization.user.read',
  'organization.user.invite',
  'organization.user.block',
  'organization.user.remove',
  'organization.user.credentials.reset',
  'organization.group.read',
  'organization.group.manage',
  'organization.role.read',
  'organization.role.manage',
  'organization.auth.manage',
  'organization.settings.manage',
  'organization.audit.read',
  'project.read',
  'project.settings.write',
  'project.archive',
  'project.delete',
  'environment.read',
  'project.lifecycle.write',
  'deployment.read',
  'deployment.create',
  'deployment.promote',
  'deployment.rollback',
  'deployment.logs.read',
  'deployment.inspect',
  'variable.metadata.read',
  'variable.value.read',
  'variable.write',
  'variable.local_run',
  'domain.read',
  'domain.write',
  'source.read',
  'source.manage',
  'app.route.access',
];

export const permissionKeysByCompartmentMembershipRole: Record<CompartmentMembershipRole, PermissionKey[]> = {
  viewer: ['project.read', 'app.route.access'],
  readonly: [
    'project.read',
    'app.route.access',
    'environment.read',
    'deployment.read',
    'deployment.logs.read',
    'deployment.inspect',
    'variable.metadata.read',
    'domain.read',
  ],
  deployer: [
    'project.read',
    'app.route.access',
    'environment.read',
    'deployment.read',
    'deployment.logs.read',
    'deployment.inspect',
    'variable.metadata.read',
    'domain.read',
    'organization.project.create',
    'deployment.create',
    'deployment.promote',
    'deployment.rollback',
    'project.lifecycle.write',
    'variable.value.read',
    'variable.write',
    'variable.local_run',
    'domain.write',
    'source.read',
  ],
  admin: [
    'project.read',
    'app.route.access',
    'environment.read',
    'deployment.read',
    'deployment.logs.read',
    'deployment.inspect',
    'variable.metadata.read',
    'domain.read',
    'organization.project.create',
    'deployment.create',
    'deployment.promote',
    'deployment.rollback',
    'project.lifecycle.write',
    'variable.value.read',
    'variable.write',
    'variable.local_run',
    'domain.write',
    'source.read',
    'project.settings.write',
    'project.archive',
    'project.delete',
    'organization.user.read',
    'organization.user.invite',
    'organization.user.block',
    'organization.user.remove',
    'organization.user.credentials.reset',
    'organization.group.read',
    'organization.group.manage',
    'organization.role.read',
    'organization.role.manage',
    'organization.auth.manage',
    'organization.settings.manage',
    'organization.audit.read',
    'source.manage',
  ],
};

export const permissionFamilyDefinitions: readonly PermissionFamilyDefinition[] = [
  {
    id: 'access-management',
    label: 'Access management',
    permissionKeys: [
      'organization.user.read',
      'organization.user.invite',
      'organization.user.block',
      'organization.user.remove',
      'organization.user.credentials.reset',
      'organization.group.read',
      'organization.group.manage',
      'organization.role.read',
      'organization.role.manage',
      'organization.auth.manage',
      'organization.settings.manage',
    ],
  },
  {
    id: 'audit-logs',
    label: 'Audit logs',
    permissionKeys: ['organization.audit.read'],
  },
  {
    id: 'project-setup',
    label: 'Project setup',
    permissionKeys: [
      'organization.project.create',
      'project.read',
      'project.settings.write',
      'project.archive',
      'project.delete',
      'source.read',
      'source.manage',
    ],
  },
  {
    id: 'deployments',
    label: 'Deployments',
    permissionKeys: [
      'environment.read',
      'project.lifecycle.write',
      'deployment.read',
      'deployment.create',
      'deployment.promote',
      'deployment.rollback',
      'deployment.logs.read',
      'deployment.inspect',
    ],
  },
  {
    id: 'runtime-configuration',
    label: 'Runtime & configuration',
    permissionKeys: ['variable.metadata.read', 'variable.value.read', 'variable.write', 'variable.local_run'],
  },
  {
    id: 'domains-routing',
    label: 'Domains & routing',
    permissionKeys: ['domain.read', 'domain.write', 'app.route.access'],
  },
];

export const friendlyAccessSummaryByRole: Record<CompartmentMembershipRole, AccessSummaryLabel> = {
  admin: 'Full access',
  deployer: 'Deploy',
  readonly: 'Read-only',
  viewer: 'Limited view',
};
