import {
  compartmentBrowserAssetsPathname,
  compartmentBrowserStartOnboardingSearchParamName,
} from '@compartment/contracts/browser';

export const browserAssetsPathname: string = `${compartmentBrowserAssetsPathname}/`;
export const browserStartOnboardingSearchParamName: string = compartmentBrowserStartOnboardingSearchParamName;

export {
  compartmentBrowserActivatePathname as browserActivatePathname,
  compartmentBrowserHomePathname as browserHomePathname,
  compartmentBrowserLoginSuccessRedirectSearchParamName as browserLoginSuccessRedirectSearchParamName,
  compartmentBrowserLoginCliCompletedPathname as browserLoginCliCompletedPathname,
  compartmentBrowserLoginCliPathname as browserLoginCliPathname,
  compartmentBrowserLoginPathname as browserLoginPathname,
  compartmentBrowserLoginSsoPathname as browserLoginSsoPathname,
  compartmentBrowserLogoutPathname as browserLogoutPathname,
  compartmentBrowserOnboardingPathname as browserOnboardingPathname,
  compartmentBrowserProjectCreatePathname as browserProjectCreatePathname,
  compartmentBrowserResetPasswordPathname as browserResetPasswordPathname,
  buildCompartmentConsoleAssetPathname as getBrowserAssetPathname,
  buildCompartmentConsoleOrganizationOnboardingPathname as buildBrowserOrganizationOnboardingPathname,
  buildCompartmentConsoleOrganizationProjectsPathname as buildBrowserOrganizationProjectsPathname,
  compartmentConsoleLoginSsoCallbackPathname as browserLoginSsoCallbackPathname,
  compartmentConsoleOrganizationAuditPathnameTemplate as browserOrganizationAuditPathnameTemplate,
  compartmentConsoleOrganizationGroupsPathnameTemplate as browserOrganizationGroupsPathnameTemplate,
  compartmentConsoleOrganizationOnboardingPathnameTemplate as browserOrganizationOnboardingPathnameTemplate,
  compartmentConsoleOrganizationProjectCreatePathnameTemplate as browserOrganizationProjectCreatePathnameTemplate,
  compartmentConsoleOrganizationProjectDeploymentDetailsPathnameTemplate as browserOrganizationProjectDeploymentDetailsPathnameTemplate,
  compartmentConsoleOrganizationProjectDeploymentsPathnameTemplate as browserOrganizationProjectDeploymentsPathnameTemplate,
  compartmentConsoleOrganizationProjectOverviewPathnameTemplate as browserOrganizationProjectOverviewPathnameTemplate,
  compartmentConsoleOrganizationProjectsPathnameTemplate as browserOrganizationProjectsPathnameTemplate,
  compartmentConsoleOrganizationRolesPathnameTemplate as browserOrganizationRolesPathnameTemplate,
  compartmentConsoleOrganizationUsersPathnameTemplate as browserOrganizationUsersPathnameTemplate,
} from '@compartment/contracts/browser';
