import type { AuditFileSinkConfigEnv } from './audit-file-sink-config';

export interface ApiConfigEnv extends AuditFileSinkConfigEnv {
  COMPARTMENT_API_BIND_HOST: string;
  COMPARTMENT_API_PORT: number;
  COMPARTMENT_BASE_DOMAIN: string;
  COMPARTMENT_CADDY_TLS_MODE: 'managed' | 'internal' | 'custom-http' | 'custom-cert';
  COMPARTMENT_CUSTOM_TLS_DIR: string;
  COMPARTMENT_DATABASE_URL: string;
  COMPARTMENT_EDGE_INTERNAL_HOST: string;
  COMPARTMENT_EDGE_PORT: number;
  COMPARTMENT_EDGE_TOKEN: string;
  COMPARTMENT_LOG_LEVEL: 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace' | 'silent';
  COMPARTMENT_MANAGED_DOMAIN_BROKER_TOKEN: string;
  COMPARTMENT_MANAGED_DOMAIN_BROKER_URL: string;
  COMPARTMENT_TRUSTED_OUTBOUND_HOSTS: string;
  COMPARTMENT_NODE_AGENT_SOCKET: string;
  COMPARTMENT_PUBLIC_PROTOCOL: 'http' | 'https';
  COMPARTMENT_PUBLIC_HTTP_PORT: number;
  COMPARTMENT_PUBLIC_HTTPS_PORT: number;
  COMPARTMENT_RUNTIME_DEFAULT_UPSTREAM_HOST: string;
  COMPARTMENT_AUDIT_RETENTION_DAYS: number;
  COMPARTMENT_AUDIT_RETENTION_CLEANUP_BATCH_SIZE: number;
  COMPARTMENT_AUDIT_RETENTION_CLEANUP_CRON: string;
  COMPARTMENT_AUDIT_RETENTION_CLEANUP_MAX_BATCHES: number;
  COMPARTMENT_ROLLBACK_RETENTION_LIMIT: string;
  COMPARTMENT_RESOURCE_BACKUP_DIR: string;
  COMPARTMENT_SOURCE_ARCHIVE_DIR: string;
  COMPARTMENT_SOURCE_ARCHIVE_MAX_BYTES: number;
  COMPARTMENT_SESSION_SECRET: string;
  COMPARTMENT_SESSION_TTL: string;
  COMPARTMENT_SYSTEM_API_SOCKET: string;
  COMPARTMENT_SYSTEM_TOKEN: string;
  COMPARTMENT_VARIABLES_MASTER_KEY: string;
  COMPARTMENT_RUNTIME_CONTROL_TOKEN: string;
}
