apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compartment-edge-snapshot
  labels:
    app.kubernetes.io/name: compartment-edge
    app.kubernetes.io/component: edge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
